### ISSUE TITLE
issues_MJ

### ISSUE THREAD

**Issue by pocketmarket-official** [pocketmarket-official/pocketmarket#3]
1
마이페이지 우측 상단 버튼 my버튼 누를시 점주 관리 페이지로 넘어감
마이페이지 하단 버튼 누른 후 우측 상단 종모양 버튼 클릭 시 my page 로 넘어감
하단메뉴리스트 클릭시 우측상단 버튼 통일

2. index화면으로 돌아가는 버튼이 없음

3. 메인 화면 우측상단 종모양 버튼 화면 없음

4. 지도보기 오류

5 지도보기 우측상단 버튼 기능 확인

6. index화면 도감, 주문확인 버튼
도감 클릭시 my page_포켓마켓도감 페이지 연결
주문확인 클릭시 _ order status 페이지 연결

7 main화면 상단 고정가능한가?
검색기능 바 고정

8 축제 매장 리스트 우측 상단 종 버튼 누를때 my page 연결됨

9 리뷰 클릭시 리뷰자세히 보기

10. 현위치 버튼 클릭시 주소지 > 현위치 변경

11.버튼 위치 흔들림

**Comment by Peter-Roh** [comment]
issue 10 resolved

**Comment by Peter-Roh** [comment]
issue #4 resolved

**Comment by Peter-Roh** [comment]
issue #8 resolved

**Comment by Peter-Roh** [comment]
issue #2 resolved

**Comment by Peter-Roh** [comment]
issue #2 resolved
